services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: sit722week72_user
      POSTGRES_PASSWORD: iakl5WLQ0ouglcGFbepRI3Tv4G4ZE78a
      POSTGRES_DB: sit722week72
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  book_catalog:
    build: ./book_catalog
    image: book_catalog
    environment:
      DATABASE_URL: postgresql://sit722week72_user:iakl5WLQ0ouglcGFbepRI3Tv4G4ZE78a@postgres:5432/sit722week72
    depends_on:
      - postgres
    ports:
      - "4001:4001"

  inventory_management:
    build: ./inventory_management
    image: inventory_management
    environment:
      DATABASE_URL: postgresql://sit722week72_user:iakl5WLQ0ouglcGFbepRI3Tv4G4ZE78a@postgres:5432/sit722week72
    depends_on:
      - postgres
    ports:
      - "4002:4002"

volumes:
  postgres_data:  # This explicitly defines the 'postgres_data' volume
